### ISSUE TITLE
The request can release the exe？

### ISSUE THREAD

**Issue by Baikeryoyo** [Porchetta-Industries/CrackMapExec#694] opened 2022-12-04 18:21 UTC
I'm having trouble installing
When I execute pip install -r requirements.txt
Failed building wheel for aardwolf

**Comment by mpgn** [comment] 2022-12-04 18:22
You need to install rust first

**Comment by Baikeryoyo** [comment] 2022-12-04 18:30
> You need to install rust first

what? I didn't see this in the installation instructions
It tells me that I only need binary files and python

**Comment by mpgn** [comment] 2023-01-01 19:16
the issue is hard to understand, closing for now until you explain a bit more

**Closed by mpgn** 2023-01-01 19:16 UTC
